"""EXPLORATORY (post-hoc, not pre-registered) analysis of an existing campaign's logs.

    python scripts/exploratory.py eval_local_v1 > docs/exploratory_tables.md

A. Clean vs anchored: the strong model's single-shot success on the CLEAN prompt
   (strong_only, attempt 1) vs with the small model's failed candidate in context
   (escalate, attempt 2, escalated runs only). Paired by task and by (task, repeat):
   the same seed is used for both policies within a repeat.
B. Two shots: how much of strong_only's success came from its second attempt.
C. Anchoring check: is the strong model's escalate candidate a copy or a small edit
   of the small model's wrong candidate? Code-only comparison (docstrings, comments
   and formatting ignored). Needs the local artifacts (not committed).

Reads only logs and artifacts; no model is called.
"""
from __future__ import annotations

import ast
import difflib
import json
import statistics
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
from routing_pilot.candidate import code_only  # noqa: E402
from routing_pilot.tasks import load_public  # noqa: E402

INSPECT = ("knapsack", "subsequences")


def load(path: Path) -> list[dict]:
    return [json.loads(l) for l in path.read_text(encoding="utf-8").splitlines() if l.strip()]


def norm(code: str | None) -> str | None:
    if code is None:
        return None
    try:
        return code_only(ast.parse(code))
    except SyntaxError:
        return None


def ndiff(a: str | None, b: str | None) -> int | None:
    if a is None or b is None:
        return None
    d = difflib.unified_diff(a.splitlines(), b.splitlines(), lineterm="", n=0)
    return sum(1 for l in d if l[:1] in "+-" and not l.startswith(("+++", "---")))


def pct(x: float) -> str:
    return f"{100 * x:.0f}%"


def main(campaign: str):
    sys.stdout.reconfigure(encoding="utf-8")
    d = ROOT / "results" / campaign
    runs = {r["run_id"]: r for r in load(d / "runs.jsonl") if r["final_status"] != "infra_error"}
    att = defaultdict(dict)
    for a in load(d / "attempts.jsonl"):
        if a["run_id"] in runs and "error_type" not in a:
            att[a["run_id"]][a["attempt"]] = a
    by = defaultdict(list)    # (policy, task) -> runs
    for r in runs.values():
        by[(r["policy"], r["task_id"])].append(r)
    tasks = sorted({r["task_id"] for r in runs.values()})

    def a1_success(r):   # attempt 1 alone resolved the run
        return r["resolved"] and r["total_calls"] == 1

    out = [f"# EXPLORATORY tables: {campaign}", "",
           "Post-hoc, not pre-registered. Generated by `scripts/exploratory.py` from the logs.", ""]

    # ---- A: clean vs anchored, per task ----
    out += ["## A. Strong model: clean prompt vs small model's failed candidate in context", "",
            "clean = strong_only attempt 1 resolves the run (all repeats). "
            "anchored = escalate attempt 2 resolves the run (escalated runs only; small failed visible tests first).", "",
            "| Task | clean (strong_only a1) | anchored (escalate a2) | escalated runs |", "|---|---|---|---|"]
    pairs_task = []
    for t in tasks:
        so = by[("strong_only", t)]
        esc = [r for r in by[("escalate", t)] if r["escalated"]]
        clean = statistics.mean(a1_success(r) for r in so)
        if esc:
            anch = statistics.mean(r["resolved"] for r in esc)
            pairs_task.append((t, clean, anch))
            out.append(f"| {t} | {sum(a1_success(r) for r in so)}/{len(so)} | {sum(r['resolved'] for r in esc)}/{len(esc)} | {len(esc)} |")
        else:
            out.append(f"| {t} | {sum(a1_success(r) for r in so)}/{len(so)} | – (small passed visible every time) | 0 |")
    if pairs_task:
        c = statistics.mean(x[1] for x in pairs_task)
        a = statistics.mean(x[2] for x in pairs_task)
        better = sum(x[1] > x[2] for x in pairs_task)
        worse = sum(x[1] < x[2] for x in pairs_task)
        out += ["", f"Tasks with at least one escalation: {len(pairs_task)}. Task-averaged success: "
                    f"clean {pct(c)} vs anchored {pct(a)} (Δ {100 * (a - c):+.1f} pp). "
                    f"Clean better on {better} tasks, anchored better on {worse}, tied on {len(pairs_task) - better - worse}."]

    # paired by (task, repeat): same seed, same task
    so_by = {(r["task_id"], r["repeat"]): r for r in runs.values() if r["policy"] == "strong_only"}
    table = defaultdict(int)
    for r in runs.values():
        if r["policy"] == "escalate" and r["escalated"]:
            s = so_by.get((r["task_id"], r["repeat"]))
            if s:
                table[(a1_success(s), r["resolved"])] += 1
    out += ["", "Paired by (task, repeat) with the same seed (escalated runs):", "",
            "| | anchored success | anchored failure |", "|---|---|---|",
            f"| clean success | {table[(True, True)]} | {table[(True, False)]} |",
            f"| clean failure | {table[(False, True)]} | {table[(False, False)]} |"]

    # where does escalate's gap to strong_only come from? pair every escalate run with strong_only (same task, repeat)
    gap = defaultdict(int)
    for r in runs.values():
        s = so_by.get((r["task_id"], r["repeat"])) if r["policy"] == "escalate" else None
        if s and r["resolved"] != s["resolved"]:
            kind = "escalated (strong a2 after small)" if r["escalated"] else "not escalated (small's answer kept)"
            gap[(kind, "escalate wins" if r["resolved"] else "strong_only wins")] += 1
    out += ["", "Decomposition of escalate vs strong_only, paired by (task, repeat):", "",
            "| Escalate run was | strong_only wins | escalate wins | net |", "|---|---|---|---|"]
    for kind in ("not escalated (small's answer kept)", "escalated (strong a2 after small)"):
        w, l = gap[(kind, "strong_only wins")], gap[(kind, "escalate wins")]
        out.append(f"| {kind} | {w} | {l} | {l - w:+d} |")

    # ---- B: two shots ----
    so = [r for r in runs.values() if r["policy"] == "strong_only"]
    res1 = sum(r["resolved"] and r["total_calls"] == 1 for r in so)
    res2 = sum(r["resolved"] and r["total_calls"] == 2 for r in so)
    two = [r for r in so if r["total_calls"] == 2]
    per_task_a1 = statistics.mean(statistics.mean(a1_success(r) for r in by[("strong_only", t)]) for t in tasks)
    per_task_all = statistics.mean(statistics.mean(r["resolved"] for r in by[("strong_only", t)]) for t in tasks)
    esc_rate = statistics.mean(statistics.mean(r["resolved"] for r in by[("escalate", t)]) for t in tasks)
    out += ["", "## B. Two shots: where strong_only's success comes from", "",
            f"- strong_only resolved {res1 + res2}/{len(so)} runs: {res1} on attempt 1, {res2} on attempt 2 "
            f"(second attempts made: {len(two)}, of which {res2} resolved).",
            f"- Task-averaged resolution: attempt 1 only {pct(per_task_a1)}; with the second attempt {pct(per_task_all)} "
            f"(+{100 * (per_task_all - per_task_a1):.1f} pp). escalate: {pct(esc_rate)}."]

    # ---- C: anchoring check ----
    out += ["", "## C. Anchoring check (code-only line differences)", "",
            "small = escalate a1 (small model's failed candidate); a2 = escalate a2 (strong model, anchored); "
            "clean = strong_only a1 at the same repeat. Numbers are changed lines after removing docstrings/comments.", "",
            "| Task | Repeat | small vs buggy | a2 vs small | a2 vs buggy | a2 vs clean | a2 == small (code) | a2 resolved | clean resolved |",
            "|---|---|---|---|---|---|---|---|---|"]
    art = d / "artifacts"
    detail = []
    for t in tasks:
        buggy = norm(load_public(ROOT / "data", t).buggy_code)
        for r in sorted(by[("escalate", t)], key=lambda r: r["repeat"]):
            if not r["escalated"]:
                continue
            read = lambda rid, n: (art / rid / f"attempt{n}_candidate.py").read_text(encoding="utf-8") \
                if (art / rid / f"attempt{n}_candidate.py").exists() else None
            small, a2 = norm(read(r["run_id"], 1)), norm(read(r["run_id"], 2))
            s = so_by.get((t, r["repeat"]))
            clean = norm(read(s["run_id"], 1)) if s else None
            row = (t, r["repeat"], ndiff(buggy, small), ndiff(small, a2), ndiff(buggy, a2), ndiff(clean, a2),
                   small is not None and small == a2, r["resolved"], bool(s and a1_success(s)))
            detail.append(row)
            if t in INSPECT:
                out.append("| " + " | ".join(str(x) for x in row) + " |")
    if detail:
        ok = [x for x in detail if x[3] is not None]
        fail = [x for x in ok if not x[7]]
        succ = [x for x in ok if x[7]]
        med = lambda xs, i: statistics.median(x[i] for x in xs) if xs else float("nan")
        out += ["", f"All escalated runs ({len(ok)} with readable candidates): a2 identical in code to the small "
                    f"candidate in {sum(x[6] for x in ok)}; a2 identical to buggy in {sum(x[4] == 0 for x in ok)}. "
                    f"Median a2-vs-small changed lines: failed a2 {med(fail, 3)}, resolved a2 {med(succ, 3)}. "
                    f"Median a2-vs-clean: failed a2 {med(fail, 5)}, resolved a2 {med(succ, 5)}."]
    print("\n".join(out))


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "eval_local_v1")
