"""EXPLORATORY (post-hoc, not pre-registered) analysis of an existing campaign's logs.

    python scripts/exploratory.py eval_local_v1 > docs/exploratory_tables.md

A. Clean vs in-context (hand-off context effect): the strong model's single-shot success on the CLEAN prompt
   (strong_only, attempt 1) vs with the small model's failed candidate in context
   (escalate, attempt 2, escalated runs only). Paired by task and by (task, repeat):
   the same seed is used for both policies within a repeat.
B. Two shots: how much of strong_only's success came from its second attempt.
C. Copy check: is the strong model's escalate candidate a copy or a small edit
   of the small model's wrong candidate? Code-only comparison (docstrings, comments
   and formatting ignored). Needs the local artifacts (not committed).

Reads only logs and artifacts; no model is called.
"""
from __future__ import annotations

import ast
import difflib
import json
import math
import statistics
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
from routing_pilot.candidate import code_only  # noqa: E402
from routing_pilot.tasks import load_public  # noqa: E402

INSPECT = ("knapsack", "subsequences")


def load(path: Path) -> list[dict]:
    return [json.loads(l) for l in path.read_text(encoding="utf-8").splitlines() if l.strip()]


def norm(code: str | None) -> str | None:
    if code is None:
        return None
    try:
        return code_only(ast.parse(code))
    except SyntaxError:
        return None


def ndiff(a: str | None, b: str | None) -> int | None:
    if a is None or b is None:
        return None
    d = difflib.unified_diff(a.splitlines(), b.splitlines(), lineterm="", n=0)
    return sum(1 for l in d if l[:1] in "+-" and not l.startswith(("+++", "---")))


def sign_test(b: int, c: int) -> float:
    """Exact two-sided sign test (McNemar exact) on discordant pair counts b vs c."""
    n, k = b + c, min(b, c)
    if n == 0:
        return 1.0
    return min(1.0, 2 * sum(math.comb(n, i) for i in range(k + 1)) / 2 ** n)


def pct(x: float) -> str:
    return f"{100 * x:.0f}%"


def main(campaign: str):
    sys.stdout.reconfigure(encoding="utf-8")
    d = ROOT / "results" / campaign
    runs = {r["run_id"]: r for r in load(d / "runs.jsonl") if r["final_status"] != "infra_error"}
    att = defaultdict(dict)
    for a in load(d / "attempts.jsonl"):
        if a["run_id"] in runs and "error_type" not in a:
            att[a["run_id"]][a["attempt"]] = a
    by = defaultdict(list)    # (policy, task) -> runs
    for r in runs.values():
        by[(r["policy"], r["task_id"])].append(r)
    tasks = sorted({r["task_id"] for r in runs.values()})

    def a1_success(r):   # attempt 1 alone resolved the run
        return r["resolved"] and r["total_calls"] == 1

    out = [f"# EXPLORATORY tables: {campaign}", "",
           "Post-hoc, not pre-registered. Generated by `scripts/exploratory.py` from the logs.", ""]

    # ---- A: clean vs in-context, per task ----
    out += ["## A. Strong model: clean prompt vs small model's failed candidate in context", "",
            "clean = strong_only attempt 1 resolves the run (all repeats). "
            "in-context = escalate attempt 2 resolves the run (escalated runs only; small failed visible tests first).", "",
            "| Task | clean (strong_only a1) | in-context (escalate a2) | escalated runs |", "|---|---|---|---|"]
    pairs_task = []
    for t in tasks:
        so = by[("strong_only", t)]
        esc = [r for r in by[("escalate", t)] if r["escalated"]]
        clean = statistics.mean(a1_success(r) for r in so)
        if esc:
            anch = statistics.mean(r["resolved"] for r in esc)
            pairs_task.append((t, clean, anch))
            out.append(f"| {t} | {sum(a1_success(r) for r in so)}/{len(so)} | {sum(r['resolved'] for r in esc)}/{len(esc)} | {len(esc)} |")
        else:
            out.append(f"| {t} | {sum(a1_success(r) for r in so)}/{len(so)} | – (small passed visible every time) | 0 |")
    if pairs_task:
        c = statistics.mean(x[1] for x in pairs_task)
        a = statistics.mean(x[2] for x in pairs_task)
        better = sum(x[1] > x[2] for x in pairs_task)
        worse = sum(x[1] < x[2] for x in pairs_task)
        out += ["", f"Tasks with at least one escalation: {len(pairs_task)}. Task-averaged success: "
                    f"clean {pct(c)} vs in-context {pct(a)} (Δ {100 * (a - c):+.1f} pp). "
                    f"Clean better on {better} tasks, in-context better on {worse}, tied on {len(pairs_task) - better - worse}."]

    # paired by (task, repeat): same seed, same task
    so_by = {(r["task_id"], r["repeat"]): r for r in runs.values() if r["policy"] == "strong_only"}
    table = defaultdict(int)
    for r in runs.values():
        if r["policy"] == "escalate" and r["escalated"]:
            s = so_by.get((r["task_id"], r["repeat"]))
            if s:
                table[(a1_success(s), r["resolved"])] += 1
    out += ["", "Paired by (task, repeat) with the same seed (escalated runs):", "",
            "| | in-context success | in-context failure |", "|---|---|---|",
            f"| clean success | {table[(True, True)]} | {table[(True, False)]} |",
            f"| clean failure | {table[(False, True)]} | {table[(False, False)]} |", "",
            f"Discordant pairs: clean-only {table[(True, False)]} vs in-context-only {table[(False, True)]}; "
            f"exact two-sided sign test p = {sign_test(table[(True, False)], table[(False, True)]):.3f} (exploratory)."]

    # where does escalate's gap to strong_only come from? pair every escalate run with strong_only (same task, repeat)
    gap = defaultdict(int)
    for r in runs.values():
        s = so_by.get((r["task_id"], r["repeat"])) if r["policy"] == "escalate" else None
        if s and r["resolved"] != s["resolved"]:
            kind = "escalated (strong a2 after small)" if r["escalated"] else "not escalated (small's answer kept)"
            gap[(kind, "escalate wins" if r["resolved"] else "strong_only wins")] += 1
    out += ["", "Decomposition of escalate vs strong_only, paired by (task, repeat):", "",
            "| Escalate run was | strong_only wins | escalate wins | net |", "|---|---|---|---|"]
    for kind in ("not escalated (small's answer kept)", "escalated (strong a2 after small)"):
        w, l = gap[(kind, "strong_only wins")], gap[(kind, "escalate wins")]
        out.append(f"| {kind} | {w} | {l} | {l - w:+d} |")

    # ---- B: two shots ----
    so = [r for r in runs.values() if r["policy"] == "strong_only"]
    res1 = sum(r["resolved"] and r["total_calls"] == 1 for r in so)
    res2 = sum(r["resolved"] and r["total_calls"] == 2 for r in so)
    two = [r for r in so if r["total_calls"] == 2]
    per_task_a1 = statistics.mean(statistics.mean(a1_success(r) for r in by[("strong_only", t)]) for t in tasks)
    per_task_all = statistics.mean(statistics.mean(r["resolved"] for r in by[("strong_only", t)]) for t in tasks)
    esc_rate = statistics.mean(statistics.mean(r["resolved"] for r in by[("escalate", t)]) for t in tasks)
    out += ["", "## B. Two shots: where strong_only's success comes from", "",
            f"- strong_only resolved {res1 + res2}/{len(so)} runs: {res1} on attempt 1, {res2} on attempt 2 "
            f"(second attempts made: {len(two)}, of which {res2} resolved).",
            f"- Task-averaged resolution: attempt 1 only {pct(per_task_a1)}; with the second attempt {pct(per_task_all)} "
            f"(+{100 * (per_task_all - per_task_a1):.1f} pp). escalate: {pct(esc_rate)}."]

    # ---- C: copy check ----
    out += ["", "## C. Does the strong model copy the small candidate? (code-only line differences)", "",
            "small = escalate a1 (small model's failed candidate); a2 = escalate a2 (strong model, small candidate in context); "
            "clean = strong_only a1 at the same repeat. Numbers are changed lines after removing docstrings/comments.", "",
            "| Task | Repeat | small vs buggy | a2 vs small | a2 vs buggy | a2 vs clean | a2 == small (code) | a2 resolved | clean resolved |",
            "|---|---|---|---|---|---|---|---|---|"]
    art = d / "artifacts"
    detail = []
    for t in tasks:
        buggy = norm(load_public(ROOT / "data", t).buggy_code)
        for r in sorted(by[("escalate", t)], key=lambda r: r["repeat"]):
            if not r["escalated"]:
                continue
            read = lambda rid, n: (art / rid / f"attempt{n}_candidate.py").read_text(encoding="utf-8") \
                if (art / rid / f"attempt{n}_candidate.py").exists() else None
            small, a2 = norm(read(r["run_id"], 1)), norm(read(r["run_id"], 2))
            s = so_by.get((t, r["repeat"]))
            clean = norm(read(s["run_id"], 1)) if s else None
            row = (t, r["repeat"], ndiff(buggy, small), ndiff(small, a2), ndiff(buggy, a2), ndiff(clean, a2),
                   small is not None and small == a2, r["resolved"], bool(s and a1_success(s)))
            detail.append(row)
            if t in INSPECT:
                out.append("| " + " | ".join(str(x) for x in row) + " |")
    if detail:
        ok = [x for x in detail if x[3] is not None]
        fail = [x for x in ok if not x[7]]
        succ = [x for x in ok if x[7]]
        med = lambda xs, i: statistics.median(x[i] for x in xs) if xs else float("nan")
        out += ["", f"All escalated runs ({len(ok)} with readable candidates): a2 identical in code to the small "
                    f"candidate in {sum(x[6] for x in ok)}; a2 identical to buggy in {sum(x[4] == 0 for x in ok)}. "
                    f"Median a2-vs-small changed lines: failed a2 {med(fail, 3)}, resolved a2 {med(succ, 3)}. "
                    f"Median a2-vs-clean: failed a2 {med(fail, 5)}, resolved a2 {med(succ, 5)}."]
    print("\n".join(out))


def compare_handoff(base: str, clean: str):
    """D. escalate (code+feedback hand-off, in `base`) vs escalate_clean (feedback only, in `clean`).
    Specified before escalate_clean_v1 was run (see the prediction in docs/exploratory.md)."""
    sys.stdout.reconfigure(encoding="utf-8")
    rb = [r for r in load(ROOT / "results" / base / "runs.jsonl") if r["final_status"] != "infra_error"]
    rc = [r for r in load(ROOT / "results" / clean / "runs.jsonl") if r["final_status"] != "infra_error"]
    a1 = lambda camp: {(a["task_id"], a["policy"], a["repeat"]): a for a in load(ROOT / "results" / camp / "attempts.jsonl")
                       if a["attempt"] == 1 and "error_type" not in a}
    a1b, a1c = a1(base), a1(clean)
    esc = {(r["task_id"], r["repeat"]): r for r in rb if r["policy"] == "escalate"}
    so = {(r["task_id"], r["repeat"]): r for r in rb if r["policy"] == "strong_only"}
    ecl = {(r["task_id"], r["repeat"]): r for r in rc if r["policy"] == "escalate_clean"}
    keys = sorted(set(esc) & set(ecl))
    out = [f"# EXPLORATORY: hand-off comparison {base} (escalate) vs {clean} (escalate_clean)", "",
           "Post-hoc, not pre-registered. Analysis specified before the escalate_clean run. "
           "Generated by `scripts/exploratory.py` from the logs.", ""]

    same_hash = sum(a1b[(t, "escalate", r)]["candidate_hash"] == a1c[(t, "escalate_clean", r)]["candidate_hash"]
                    for t, r in keys if (t, "escalate", r) in a1b and (t, "escalate_clean", r) in a1c)
    same_status = sum(a1b[(t, "escalate", r)]["public_status"] == a1c[(t, "escalate_clean", r)]["public_status"]
                      for t, r in keys if (t, "escalate", r) in a1b and (t, "escalate_clean", r) in a1c)
    out += ["## Reproducibility of the small model's first attempt (same prompt, same seed)", "",
            f"- candidate_hash identical to {base}: {same_hash}/{len(keys)}",
            f"- visible-test outcome identical: {same_status}/{len(keys)}", ""]

    both = [k for k in keys if esc[k]["escalated"] and ecl[k]["escalated"]]
    only_b = [k for k in keys if esc[k]["escalated"] and not ecl[k]["escalated"]]
    only_c = [k for k in keys if ecl[k]["escalated"] and not esc[k]["escalated"]]
    t2 = defaultdict(int)
    for k in both:
        t2[(ecl[k]["resolved"], esc[k]["resolved"])] += 1
    b, c = t2[(True, False)], t2[(False, True)]
    out += ["## Primary: pairs escalated in both campaigns", "",
            f"Pairs: {len(both)}. Escalated in only {base}: {len(only_b)}; only in {clean}: {len(only_c)} "
            "(reported, not in the primary comparison).", "",
            "| | escalate resolved | escalate failed |", "|---|---|---|",
            f"| escalate_clean resolved | {t2[(True, True)]} | {b} |",
            f"| escalate_clean failed | {t2[(False, True)]} | {t2[(False, False)]} |", "",
            f"Discordant pairs: escalate_clean-only {b} vs escalate-only {c}; "
            f"exact two-sided sign test p = {sign_test(b, c):.3f} (exploratory).", ""]

    # secondary: feedback-only hand-off vs the strong model's clean single shot (strong_only a1), same pairs
    t3 = defaultdict(int)
    for k in both:
        s = so.get(k)
        if s:
            t3[(ecl[k]["resolved"], s["resolved"] and s["total_calls"] == 1)] += 1
    b3, c3 = t3[(True, False)], t3[(False, True)]
    out += ["## Secondary: escalate_clean attempt 2 vs strong_only attempt 1 (clean single shot), same pairs", "",
            f"Discordant pairs: escalate_clean-only {b3} vs clean-single-shot-only {c3}; "
            f"exact two-sided sign test p = {sign_test(b3, c3):.3f} (exploratory).", ""]

    by = defaultdict(list)
    for r in rb + rc:
        by[r["policy"]].append(r)
    out += ["## Overall (descriptive)", "",
            "| Policy | Campaign | Resolution (task-avg) | Solved/Runs | Total cost $ | Mean calls | Escalation |",
            "|---|---|---|---|---|---|---|"]
    for pol in ("strong_only", "escalate", "escalate_clean", "small_only"):
        rs = by.get(pol)
        if not rs:
            continue
        per_task = defaultdict(list)
        for r in rs:
            per_task[r["task_id"]].append(r["resolved"])
        rate = statistics.mean(statistics.mean(v) for v in per_task.values())
        escl = f"{100 * statistics.mean(r['escalated'] for r in rs):.0f}%" if pol.startswith("escalate") else "n/a"
        out.append(f"| {pol} | {rs[0]['campaign']} | {pct(rate)} ({100 * rate:.1f}) | {sum(r['resolved'] for r in rs)}/{len(rs)} | "
                   f"{sum(r['total_cost_usd'] for r in rs):.4f} | {statistics.mean(r['total_calls'] for r in rs):.2f} | {escl} |")

    changed = [(k, esc[k]["resolved"], ecl[k]["resolved"]) for k in both if esc[k]["resolved"] != ecl[k]["resolved"]]
    out += ["", "Discordant pairs (task, repeat): " +
            (", ".join(f"{t} r{r} ({'clean hand-off wins' if c_ else 'code hand-off wins'})"
                       for (t, r), _, c_ in changed) or "none")]
    print("\n".join(out))


if __name__ == "__main__":
    if len(sys.argv) == 3:
        compare_handoff(sys.argv[1], sys.argv[2])
    else:
        main(sys.argv[1] if len(sys.argv) > 1 else "eval_local_v1")
